
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameObjectInterface.sol";
// This is class that describes you smart contract.
contract GameObject is GameObjectInterface{
    int public hp = 10;
    int public def = 0;
    address public attacker;
    function isObjectDead() private {
        tvm.accept();
        if (hp < 1) {
            die();
        }
    }
    function takeDefPower(int defense) virtual external {
        tvm.accept();
        def = defense;
    }
    function takeAttack(int value) virtual external override {
        tvm.accept();
        attacker = msg.sender;
        if (def - value < 0) {
            hp = hp - value + def;
        }
        if (hp <= 0) {
            attacker.transfer(1, false, 160);
        }
        
    }

    function die() virtual public {
        tvm.accept();
        sendAllandDestroy();

    }
    function sendAllandDestroy() public {
        require(msg.pubkey() == tvm.pubkey(), 100);
		tvm.accept();
        attacker.transfer(1, false, 160);
    }

}
